version: '3.6'

services:
  api:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    image: quay.io/go-skynet/local-ai:v2.5.1-cublas-cuda12-ffmpeg
    # image: localai/localai:v2.5.1-cublas-cuda12-core
    tty: true # enable colorized logs
    restart: always # should this be on-failure ?
    ports:
      - 8180:8180
      - 8080:8180
    env_file:
      - eg.env
    volumes:
      - ./models:/models:cached
      - ./images/:/tmp/generated/images/
    command: [ "/usr/bin/local-ai" ]
